const portfolioStore = [

	{
		id: 'tocScreenprint',
		title: 'TOC Screenprint',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Industrial design',
		type: 'img',
		description: '',
	},
	{
		id: 'aromaDiffuser',
		title: 'Aroma diffuser',
		autor: 'Petr Mojžíšek',
		year: '2017',
		category: 'Product design',
		type: 'img',
		description: '',
	},
	{
		id: 'kitchenBrush',
		title: 'Kitchen brush',
		autor: 'Petr Mojžíšek',
		year: '2016',
		category: 'Product design',
		type: 'img',
		description: '',
	},
		{
		id: 'studentContainer',
		title: 'Student container 14,95 m2',
		autor: 'Petr Mojžíšek',
		year: '2017',
		category: 'Industrial design',
		type: 'img',
		description: '',
	},
		{
		id: 'bowtieSurf',
		title: 'Bow tie_SURF',
		autor: 'Petr Mojžíšek',
		year: '2017',
		category: 'Product design',
		type: 'img',
		description: '',
	},
		{
		id: 'cameraStrap',
		title: 'Camera strap',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Product design',
		type: 'img',
		description: '',
	},
		{
		id: 'surf76',
		title: 'Surf 7\'6"',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Product design',
		type: 'img',
		description: '',
	},
		{
		id: 'skateWax',
		title: 'Skate wax',
		autor: 'Petr Mojžíšek',
		year: '2016',
		category: 'Product design',
		type: 'img',
		description: '',
	},
];

export default portfolioStore;