const portfolioStore = [

	{
		id: 'tocScreenprint',
		title: 'TOC Screenprint',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Industrial design',
		type: 'img',
		description: '',
	},
	{
		id: 'aromaDiffuser',
		title: 'Aroma diffuser',
		autor: 'Petr Mojžíšek',
		year: '2017',
		category: 'Product design',
		type: 'img',
		description: '',
	},
	{
		id: 'kitchenBrush',
		title: 'Kitchen brush',
		autor: 'Petr Mojžíšek',
		year: '2016',
		category: 'Product design',
		type: 'img',
		description: '',
	},
		{
		id: 'studentContainer',
		title: 'Student container 14,95 m2',
		autor: 'Petr Mojžíšek',
		year: '2017',
		category: 'Industrial design',
		type: 'img',
		description: '',
	},
		{
		id: 'bowtieSurf',
		title: 'Bow tie_SURF',
		autor: 'Petr Mojžíšek',
		year: '2017',
		category: 'Product design',
		type: 'img',
		description: '',
	},
		{
		id: 'cameraStrap',
		title: 'Camera strap',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Product design',
		type: 'img',
		description: '',
	},
		{
		id: 'surf76',
		title: 'Surf 7\'6"',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Product design',
		type: 'img',
		description: '',
	},
		{
		id: 'skateWax',
		title: 'Skate wax',
		autor: 'Petr Mojžíšek',
		year: '2016',
		category: 'Product design',
		type: 'img',
		description: '',
	},
		{
		id: 'akSovicka',
		title: 'AK Sovička',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Branding',
		type: 'img',
		description: '',
	},
		{
		id: 'klimatizaceOne',
		title: 'Klimatizace ONE',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Branding',
		type: 'img',
		description: '',
	},
		{
		id: 'moravskyKras',
		title: 'Moravský kras',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Branding',
		type: 'img',
		description: '',
	},
		{
		id: 'montdum',
		title: 'Montdum',
		autor: 'Petr Mojžíšek',
		year: '2018',
		category: 'Branding',
		type: 'img',
		description: '',
	},
	{
		id: 'jakubZak',
		title: 'Jakub Žák - osobní kouč',
		autor: 'Michal Dovrtěl',
		year: '2018',
		category: 'Branding',
		type: 'img',
		description: '',
	},
		{
		id: 'airstreeemConfigurator',
		title: 'Aistreeem.com GmbH',
		autor: 'Michal Dovrtěl',
		year: '2017',
		category: 'Grafika',
		type: 'img',
		description: '',
	},
			{
		id: 'fitMonster',
		title: 'Fit Monster partners guide',
		autor: 'Michal Dovrtěl',
		year: '2016',
		category: 'Grafika',
		type: 'img',
		description: '',
	},
				{
		id: 'brnoMap',
		title: 'Brno map icons',
		autor: 'Michal Dovrtěl',
		year: '2016',
		category: 'Grafika',
		type: 'img',
		description: '',
	},
				{
		id: 'randomIllustrations',
		title: 'Random illustrations',
		autor: 'Michal Dovrtěl, Petr Mojžíšek',
		year: '2016 - present',
		category: 'Grafika',
		type: 'img',
		description: '',
	},
				{
		id: 'konopnyTata',
		title: 'Konopný Táta',
		autor: 'Petr Mojžíšek',
		year: '2016 - present',
		category: 'Branding',
		type: 'img',
		description: '',
	},
				{
		id: 'elementStore',
		title: 'Element Store',
		autor: 'Petr Mojžíšek',
		year: '2016 - present',
		category: 'Grafika',
		type: 'img',
		description: '',
	},
			{
		id: 'yvycom',
		title: 'yvycom.com',
		autor: 'Michal Dovrtěl',
		year: '2017',
		category: 'Web',
		type: 'img',
		description: '',
	},
			{
		id: 'twixtax',
		title: 'twixtax.cz',
		autor: 'Michal Dovrtěl',
		year: '2014',
		category: 'Web',
		type: 'img',
		description: '',
	},
		{
		id: 'andox',
		title: 'andox.cz',
		autor: 'Michal Dovrtěl',
		year: '2017',
		category: 'Web',
		type: 'img',
		description: '',
	},
		{
		id: 'jbbagry',
		title: 'jbbagry.cz',
		autor: 'Michal Dovrtěl + Petr Mojžíšek',
		year: '2017',
		category: 'Web',
		type: 'img',
		description: '',
	},
		{
		id: 'montdumWeb',
		title: 'montdum.cz',
		autor: 'Michal Dovrtěl + Petr Mojžíšek',
		year: '2018',
		category: 'Web',
		type: 'img',
		description: '',
	},
	{
		id: 'dataBrno',
		title: 'montdum.cz',
		autor: 'Michal Dovrtěl + Petr Mojžíšek',
		year: '2018',
		category: 'Web',
		type: 'img',
		description: '',
	},
	{
		id: 'naproti',
		title: 'Naproti',
		autor: 'Petr Konšel',
		year: '2017',
		category: 'Foto',
		type: 'img',
		description: '',
	},
	{
		id: 'elmesy',
		title: 'Elmesy s.r.o.',
		autor: 'Petr Konšel',
		year: '2017',
		category: 'Foto',
		type: 'img',
		description: '',
	},
	{
		id: 'univerzitka',
		title: 'Univerzitka',
		autor: 'Petr Konšel',
		year: '2017',
		category: 'Foto',
		type: 'img',
		description: '',
	},
		{
		id: 'acuteDose',
		title: 'Acute Dose',
		autor: 'Petr Konšel',
		year: '2017',
		category: 'Foto',
		type: 'img',
		description: '',
	},
			{
		id: 'mysakDh',
		title: 'Myšák DH Cup',
		autor: 'Petr Konšel',
		year: '2017',
		category: 'Foto',
		type: 'img',
		description: '',
	},
			{
		id: 'avmedia',
		title: 'AV Media',
		autor: 'Petr Konšel',
		year: '2017',
		category: 'Foto',
		type: 'img',
		description: '',
	},
];

export default portfolioStore;